fix!: Rename package to match name inferred from git URL
awslabs/smithy-swift pull request #464
Opened 2022-11-04 16:28 UTC by jbelkins

## Description of changes
Change the declared name of this package to match its inferred name (i.e. the last path component of its Git URL, minus the extension).  This is being performed in conjunction with similar renames of `aws-sdk-swift` and `smithy-swift`.  A complete rationale for making this change is given in [this PR](https://github.com/awslabs/aws-sdk-swift/pull/678).

**This is a breaking change** but consumers of this package simply need to update their `Package.swift` to refer to the package by the new name.

## Scope
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-11-07 21:16 UTC, ganeshnj requested changes

2022-11-07 21:16 UTC, ganeshnj commented on smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/PackageManifestGenerator.kt
> -                        writer.write(".product(name: \"SmithyTestUtil\", package: \"ClientRuntime\")")
Few things must be verified
- Individual package build located at /Users/jangirg/Projects/Amplify/SwiftSDK/aws-sdk-swift/codegen/sdk-codegen/build/smithyprojections/sdk-codegen/{service}/swift-codegen
- when packages are staged in  `release`
- opening aws-crt-swift in xcode
- opening smityh-swift in xcode
- opening aws-sdk-swift in xcode without staged changes
- opening aws-sdk-swift in xcode with staged changes

2022-11-08 16:48 UTC, jbelkins commented on smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/PackageManifestGenerator.kt
> -                        writer.write(".product(name: \"SmithyTestUtil\", package: \"ClientRuntime\")")
The broken `Package.swift` above is fixed in https://github.com/awslabs/aws-sdk-swift/pull/678/commits/f290fd48c428584dc7f509be83a074efe4d2d2b6

2022-11-08 21:30 UTC, jbelkins commented on smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/PackageManifestGenerator.kt
> -                        writer.write(".product(name: \"SmithyTestUtil\", package: \"ClientRuntime\")")
@ganeshnj All the situations you described have been tested out.  I generated a release then built out all services as well.

2022-11-08 23:55 UTC, ganeshnj commented on smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/PackageManifestGenerator.kt
> -                        writer.write(".product(name: \"SmithyTestUtil\", package: \"ClientRuntime\")")
Thanks for testing. This is painful but needed until we have a better CI checks for such cases.

2022-11-08 23:55 UTC, ganeshnj approved these changes

2022-11-09 14:41 UTC, merged